apiVersion: v1
kind: ConfigMap
metadata:
  name: zar-transactions-service-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  JWT_SECRET_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMDA4MTcxNywiaWF0IjoxNzIwMDgxNzE3fQ.pVVn3P7Fzl62b6O-Qge0TpUiA75zu1rNGXpzwykkRHc"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
