apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-charts.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "my-charts.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-charts.name" . }}
    spec:
      containers:
      - name: {{ include "my-charts.name" . }}
        image: aliquis21/zar-transactions-service:latest
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zar-transactions-service-secrets
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: zar-transactions-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
        volumeMounts:
        - name: photos-storage
          mountPath: /app/photos
      volumes:
      - name: photos-storage
        persistentVolumeClaim:
          claimName: zar-photos-pvc
      imagePullSecrets:
        - name: regcred
