apiVersion: v1
kind: Secret
metadata:
  name: zar-transactions-service-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vdXNlcm5hbWU6cGFzc3dvcmRAcG9zdGdyZXNzLXNlcnZpY2U6NTQzMi92emFydWJpbg==
  # base64-строка для подключения: postgresql+asyncpg://username:password@postgres-service:5432/vzarubin
