apiVersion: v1
kind: Service
metadata:
  name: zar-transactions-service
  namespace: test
spec:
  selector:
    app: zar-transactions-service
  ports:
  - protocol: TCP
    port: 83
    targetPort: 8080
  type: ClusterIP
